apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEF5TURReApNelE0TVRkYUZ3MDBNVEF5TURReE16UTRNVGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDOUVvZjJLM0FDRkgwTzhYTVl1TjVvU3dyeHRwZEorc3F3L1ArQUhPNEtoZ1lVcFdLVApFQmlRUFplN015clhFRklXS3VTZmRrY0h4cU93WWRCYkpqa0dEemZZOXNaWkFlZ3l0OGtHTVBqY3NEMzdiNGxLCnlXWHJlb1lnRlNDSVczdWRVQU9Ldy8wdVZHcFZXYzA2clJSVkZkcVZzcVlDYXpacDFHRkZNWEhLSVorbmhxb1cKWWxUSkYyRjdMelF4WGdUUGtBMDVWdDZUZVh2Z1VxR1RFbENYQ2duOXZaNnRVV1NUT0hhdUNubWtORGh0MHVyWAozbE5Bb3JGSUp3YjREZGRzei9rZnduTEVEcGpvRk04bWxhbkZ5SGFnd2pZZ2grTjVLKzRaNUx5bVlINTRvVUxlCjFrVUQwQ21pQm0za3pVOXpvNW51MXpTekRsbWtHMVFmRDlRVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFVZzhiWHYyNFBpMnpNb09rLwpQVHU1eVdUczZqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFheDJQdy9SOHNKOUdxV2x0YW9mYzBkcytHSzRqCjJ4b2czeVlnbi9TMm5wSTEyM2NRNHY5b0IxcFBoV1RyTkN5T2piUFB1bzdTNTJKU1hhNTJBa09YSUJqQTloN2EKRVBmTE1MelVKMzMxNVpSM3FkVWRnRHBFU2pYeDhDNHhsZTdWQ3VMa1BJaHBLRVFtaDU4UDBNMVlSNXVCUDRRYQowbk9mS2dpb2xWZTA0b21mNUhaZGtHQ3p3MHl0MC81VURDdnQwVzc5RURmMjZEZ3FyRnBXV2cyUm5CTjd2T3R0ClBEMC8wbEorb3FJOEFITDlrUDRkMHFrbGxQSXJoTmc4UVM5bGhSejFZWjZyUHU2dlo0Z280MlBGMUp6cWpHdUIKbHR0NGVmWXI0eXIydyt2ZEdqZGdmL3pQSTk2KzhLMWVva00yRlAyNlMwd1VJNDFQMkQrRzhDZzI4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3354e5ba-e23d-4e10-9b75-4bedb65843c6.k8s.ondigitalocean.com
  name: do-nyc1-k8s-1-20-2-do-0-nyc1-1612446412039
contexts:
- context:
    cluster: do-nyc1-k8s-1-20-2-do-0-nyc1-1612446412039
    user: do-nyc1-k8s-1-20-2-do-0-nyc1-1612446412039-admin
  name: do-nyc1-k8s-1-20-2-do-0-nyc1-1612446412039
current-context: do-nyc1-k8s-1-20-2-do-0-nyc1-1612446412039
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-1-20-2-do-0-nyc1-1612446412039-admin
  user:
    token: 151e149e5533b7939ac8767b7e6ba242ee0934eaf33278830b7082351d7ee939
