apiVersion : apps/v1
kind: Deployment
metadata:
  name: "salzer4-68c4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "salzer4-68c4"
  template:
    metadata:
      labels:
        app: "salzer4-68c4"
    spec:
      containers:
        - name: "salzer4-68c4"
          image: "blockchainjava.azurecr.io/salzer4"
          ports:
          - containerPort: 8080