apiVersion: v1
kind: Service
metadata:
    name: "salzer4-68c4"
    labels:
        app: "salzer4-68c4"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "salzer4-68c4"